rgname = "padev1"
rglocation = "eastus"
app_insights_name = "springAppinsights"
law_name = "devloganalyticsworkspace"
sc_service_name = "devappservice"
azure_bastion_subnet = "scbastionsubnet"
sc_pip = "bastionpip"
sc_bastion_host = "scbastionhost"
